# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop if a build fails to resolve them
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Mod Properties
mod_version=1.1.0
maven_group=com.naglyadno
archives_base_name=speedhunt

# Dependencies
# check this on https://fabricmc.net/develop (Fabric API row for your minecraft_version)
fabric_version=0.116.0+1.21.1
